### ISSUE TITLE
Hellfire as a mod

### ISSUE THREAD

**Issue by SoapyNinja** [sergi4ua/equine#1]
hellfire doesn't show up on the mod list when installed. 
The dark and purgatory mods give me an error about directx 3 
Maybe I am just doing something wrong?

**Comment by sergi4ua** [comment]
Hellfire is currently not fully supported (in the older versions the launcher won't even launch without vanilla Diablo). Hellfire will be officially supported in EQUINE in the new version.
About The Dark and Purgatory... weird... did you try launching it with a different ddraw wrapper? Also try downloading and installing this: https://www.microsoft.com/en-us/download/details.aspx?id=5555 and this: https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by SoapyNinja** [comment]
Ok so maybe in the future.
I got he dark and purgatory to run you just have to enable compatibility mode on the exe itself to xp.
I did get a error when trying to load a game in both for not having the cd in (i have it mounted) I can run hellfire without equine.  
It does the same thing when you try to run just the mod exe file too so maybe its a mod issue?

**Comment by SoapyNinja** [comment]
I got both the mods to work. I had to copy all the mpq files (hellfire.mpq hfmonk.mpq hfmusic.mpq and hfvoice.mpq) to the diablo directory and they both load up fine now.

**Comment by sergi4ua** [comment]
Glad it worked :)
If you encounter any bugs please let me know :)
