### ISSUE TITLE
Error when downloading or force updating a mod

### ISSUE THREAD

**Issue by brunocar** [sergi4ua/equine#4]
I made a new install of Equine to replace my old CD install, using the GOG version, the new install gets an error about invalid data when downloading and force updating mods, it works fine with mods i copied over from my original install tho.

EDIT: i installed it on the main diablo folder, not on the DX folder, but vanilla boots fine

**Comment by sergi4ua** [comment]
Fixed by af322a0 commit. Please wait a few minutes for changes to take affect.

**Comment by sergi4ua** [comment]
I've also fixed Force Updating the game to 1.09(b) and the downgrader. Thanks again 👍

**Comment by brunocar** [comment]
Thanks to you!
