### ISSUE TITLE
It seems the commit that fixed the downloading broke the "open mod folder" feature

### ISSUE THREAD

**Issue by brunocar** [sergi4ua/equine#5]
It doesnt even work with vanilla, which it did work before.

**Comment by sergi4ua** [comment]
This bug occurs randomly for some reason. Expect an update today or tomorrow.

**Comment by sergi4ua** [comment]
The bug is fixed in the 0.8.1c update. You should get the update immediately the next time you run EQUINE. Thanks for reporting 👍

**Comment by brunocar** [comment]
I can confirm its fixed.
